name: Build and Download

on:
    push:
        branches: [main]
    pull_request:

env:
    DEBUG: 'napi:*'

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable

            - name: Check formatting
              run: cargo fmt --all --check

            - name: Clippy
              run: cargo clippy

    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  toolchain: stable
                  targets: x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu

            - uses: Swatinem/rust-cache@v2

            - run: cargo install cargo-xwin

            - name: Node install
              run: npm ci

            - name: Build Linux
              run: npm run build -- --target x86_64-unknown-linux-gnu

            - name: Build Windows
              run: npm run build -- --target x86_64-pc-windows-msvc

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: OS specific binaries
                  path: dist
                  if-no-files-found: error

    download-binaries:
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: OS specific binaries
                  path: dist/

            - name: List downloaded files
              run: |
                  echo "- Root directory:" && ls
                  echo "- Dist directory:" && ls -R dist
